name: Style Dictionary Workflow

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: 'https://npm.pkg.github.com'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable --immutable-cache --check-cache
      - name: Build package
        uses: borales/actions-yarn@v4
        with:
          cmd: build
